biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_fmt:
- 2023.2.0.dev0+69.g455a329
qiime2_epoch:
- '2023.5'
r_base:
- '>=4.2.0'
rescript:
- 2022.8.0+3.g2ff974b
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
