hdf5:
- '*'
pandas:
- 1.2.*
python:
- '3.8'
q2_alignment:
- 2022.4.0.dev0
q2_composition:
- 2022.4.0.dev0
q2_diversity_lib:
- 2022.4.0.dev0
q2_emperor:
- 2022.4.0.dev0
q2_metadata:
- 2022.4.0.dev0
q2_mystery_stew:
- 2022.4.0.dev0
q2_quality_control:
- 2022.4.0.dev0
q2_sample_classifier:
- 2022.4.0.dev0
qiime2_epoch:
- '2022.4'
scikit_learn:
- 0.24.1
unifrac:
- '*'
