hdf5:
- '*'
pandas:
- 1.2.*
python:
- '3.8'
q2_cutadapt:
- 2022.4.0.dev0
q2_dada2:
- 2022.4.0.dev0
q2_deblur:
- 2022.4.0.dev0
q2_demux:
- 2022.4.0.dev0
q2_feature_classifier:
- 2022.4.0.dev0
q2_fragment_insertion:
- 2022.4.0.dev0
q2_gneiss:
- 2022.4.0.dev0
q2_longitudinal:
- 2022.4.0.dev0
qiime2_epoch:
- '2022.4'
scikit_learn:
- 0.24.1
unifrac:
- '*'
