hdf5:
- 1.10.6
pandas:
- 1.2.*
python:
- '3.8'
q2_alignment:
- 2022.2.0.dev0
q2_feature_table:
- 2022.2.0.dev0
q2_taxa:
- 2022.2.0.dev0
qiime2_epoch:
- '2022.2'
scikit_learn:
- 0.24.1
unifrac:
- 0.20.2
