name: gha-prototype

on:
  pull_request:
    paths:
      - .github/**

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      distros: ${{ steps.config.outputs.distros }}
      epochs: ${{ steps.config.outputs.epochs }}
    steps:
      - name: config
        run: |
          # bash arrays, space separated
          DISTROS="core"
          EPOCHS="2022.4"

          echo "::set-output name=distros::$(jq -nc '$ARGS.positional' --args $DISTROS)"
          echo "::set-output name=epochs::$(jq -nc '$ARGS.positional' --args $EPOCHS)"

  integrate:
    needs: config
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        distro: ${{ fromJson(needs.config.outputs.distros) }}
        epoch: ${{ fromJson(needs.config.outputs.epochs) }}
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: destructure metapackage
        id: destructure
        uses: ./.github/actions/destructure-metapackage
        with:
          distro: ${{ matrix.distro }}
          epoch: ${{ matrix.epoch }}
