name: gha-prototype

on:
  pull_request:
    paths:
      - .github/**

jobs:
  integrate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        distro:
          - core
        epoch:
          - '2022.4'
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: destructure metapackage
        id: destructure
        uses: ./.github/actions/destructure-metapackage
        with:
          distro: ${{ matrix.distro }}
          epoch: ${{ matrix.epoch }}

      - name: debug
        run: |
          echo "${{ steps.destructure.outputs.spec }}"
