name: gha-prototype

on:
  pull_request:
    paths:
      - .github/**

jobs:
  config:
    runs-on: ubuntu-latest
    env:
      PLATFORM: ubuntu-latest
      DISTRO: core
      EPOCH: 2022.4
    outputs:
      platform: ${{ steps.set-vars.outputs.platform }}
      distro: ${{ steps.set-vars.outputs.distro }}
      epoch: ${{ steps.set-vars.outputs.epoch }}
    steps:
      - name: set-vars
        id: set-vars
        run: |
          echo "::set-output name=platform::$PLATFORM"
          echo "::set-output name=distro::$DISTRO"
          echo "::set-output name=epoch::$EPOCH"

  integrate:
    needs: config
    runs-on: ${{ needs.config.outputs.platform }}
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: destructure metapackage
        id: destructure
        uses: ./.github/actions/destructure-metapackage
        with:
          distro: ${{ needs.config.outputs.distro }}
          epoch: ${{ needs.config.outputs.epoch }}

  debug:
    needs: [config, integrate]
    runs-on: ${{ needs.config.outputs.platform }}
    steps:
      - name: debug
        run:
          echo 'pkgs: ${{ needs.integrate.outputs.pkgs }}'
          echo 'metapackage-spec: ${{ needs.integrate.outputs.metapackage-spec }}'
          echo 'q2-channel: ${{ needs.integrate.outputs.q2-channel }}'

  test-package:
    name: test ${{ matrix.pkg.name }}
    needs: [config, integrate]
    runs-on: ${{ needs.config.outputs.platform }}
    strategy:
      fail-fast: false
      matrix:
        pkg: ${{ fromJson(needs.integrate.outputs.pkgs) }}
    steps:
      - name: configure conda and friends
        uses: ./.github/actions/configure-conda

      - name: run test
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate base
          wget ${{ matrix.pkg.url }}
          sudo conda build -q \
            -c ${{ needs.integrate.outputs.q2_channel }} \
            -c conda-forge \
            -c bioconda \
            -c defaults \
            --extra-deps ${{ needs.integrate.outputs.metapackage_spec }} \
            -t "*.tar.bz2"
